CREATE TABLE datasus_data ( NUMERODO varchar, TIPOBITO varchar, DTOBITO varchar, natural_ varchar,
DTNASC varchar,
IDADE int,
SEXO int,
RACACOR int,
ESTCIV int,
ESC varchar,
OCUP varchar,
CODBAIRES varchar, codmunres varchar,
LOCOCOR varchar, codestab varchar,
CODMUNOCOR varchar,
IDADEMAE int, ESCMAE int, OCUPMAE int,
QTDFILVIVO int, QTDFILMORT int, GRAVIDEZ int,
GESTACAO int, PARTO int, OBITOPARTO int, PESO int, OBITOGRAV int,
OBITOPUERP int, ASSISTMED int, EXAME int, CIRURGIA int, NECROPSIA int,
CAUSABAS varchar, LINHAA varchar, LINHAB varchar, LINHAC varchar, LINHAD varchar,
LINHAII varchar, ATESTANTE varchar, CIRCOBITO varchar, ACIDTRAB varchar, FONTE varchar, UFINFORM varchar, HORAOBITO varchar, CODBAIOCOR varchar, NUMERODN varchar, TPASSINA varchar, DTATESTADO varchar, TPPOS varchar, DTINVESTIG varchar, CAUSABAS_O varchar, DTCADASTRO varchar, FONTEINV varchar, DTRECEBIM varchar, CB_PRE varchar, CODINST varchar, MORTEPARTO varchar, TPOBITOCOR varchar, ORIGEM varchar, DTCADINV varchar, DTCADINF varchar, NUMERODV varchar, NUMSUS varchar, COMUNSVOIM varchar, DTRECORIG varchar, DTRECORIGA varchar, CAUSAMAT varchar, ESC2010 varchar, ESCMAE2010 varchar, STDOEPIDEM varchar, STDONOVA varchar, EXPDIFDATA varchar, CODMUNCART varchar, CODCART varchar, NUMREGCART varchar, DTREGCART varchar, SERIESCFAL varchar, DTCONCASO varchar, ESCMAEAGR1 varchar, ESCFALAGR1 varchar, SERIESCMAE varchar, SEMAGESTAC varchar, TPMORTEOCO varchar, DIFDATA varchar, DTCONINV varchar, NUDIASOBIN varchar, CODMUNNATU varchar, ESTABDESCR varchar, CRM varchar, NUMEROLOTE varchar, VERSAOSIST varchar, STCODIFICA varchar, CODIFICADO varchar, VERSAOSCB varchar, ATESTADO varchar, NUDIASOBCO varchar, FONTES varchar, TPRESGINFO varchar, TPNIVELINV varchar, NUDIASINF varchar, FONTESINF varchar, ALTCAUSA varchar, DO_ varchar, CARTORIO varchar, REGISTRO varchar, DATAREG varchar, DATAOBITO varchar, ESTCIVIL varchar );
